variables:
  DOCKER_IMAGE: registry.gitlab.com/leon.hoppe/betteriserv

build-frontend:
  image: docker:latest
  stage: build
  script: 
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
    - docker build -t $DOCKER_IMAGE:frontend BetterIServ.Mobile/
    - docker push $DOCKER_IMAGE:frontend

build-backend:
  image: docker:latest
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD registry.gitlab.com
    - docker build -t $DOCKER_IMAGE:backend BetterIServ.Backend/
    - docker push $DOCKER_IMAGE:backend
